#http://localhost:8080/aluno
#http://localhost:8080/h2-console
spring.application.name=superqt
server.servlet.session.tracking-modes=cookie
server.port=8080
# Config. H2
# spring.datasource.url=jdbc:h2:tcp://localhost/~/quizsupertitas
spring.datasource.url=jdbc:h2:mem:superqt
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=always

#Config JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true